---
- name: debug and see wp-rocket clean file location
  debug:
    msg: "{{ deploy_helper.shared_path }}"

- name: Template wp-rocket-clean.php
  template:
    src: ../templates/wp-rocket-clean.php.j2
    dest: "{{ deploy_helper.shared_path }}/wp-rocket-clean.php"

- name: Purge WP Rocket cache
  command: wp eval-file "{{ deploy_helper.shared_path }}/wp-rocket-clean.php"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
